name: ESP-IDF CI

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build with ESP-IDF
      uses: kaspernyhus/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.3.1
        target: esp32